//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kozvetito.Areas.allas.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("kozvetito.Areas.allas.Resource.MainLang", typeof(MainLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adminisztrátori ismeretek.
        /// </summary>
        public static string admin_ism {
            get {
                return ResourceManager.GetString("admin_ism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felveendő alkalmazottak száma.
        /// </summary>
        public static string alk_szama {
            get {
                return ResourceManager.GetString("alk_szama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Álláslehetőségek.
        /// </summary>
        public static string allaslehetosegek {
            get {
                return ResourceManager.GetString("allaslehetosegek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Árak.
        /// </summary>
        public static string arak {
            get {
                return ResourceManager.GetString("arak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Az oldal megtekintéséhez be kell jelentkezned a bal oldalon található bejelentkezési űrlap segítségével.
        ///Ha még nem vagy tagja az oldalnak, akkor a regisztrálnod kell..
        /// </summary>
        public static string be_kell_jelentkezni {
            get {
                return ResourceManager.GetString("be_kell_jelentkezni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bejelentkezes.
        /// </summary>
        public static string bejelentkezes {
            get {
                return ResourceManager.GetString("bejelentkezes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bejelentkezve.
        /// </summary>
        public static string bejelentkezve {
            get {
                return ResourceManager.GetString("bejelentkezve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belép.
        /// </summary>
        public static string belep {
            get {
                return ResourceManager.GetString("belep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beszélt nyelvek.
        /// </summary>
        public static string beszelt_nyelv {
            get {
                return ResourceManager.GetString("beszelt_nyelv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emlékezzen rám?.
        /// </summary>
        public static string emlekezzen_ram {
            get {
                return ResourceManager.GetString("emlekezzen_ram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felhasználói ismeretek.
        /// </summary>
        public static string felhasz_ism {
            get {
                return ResourceManager.GetString("felhasz_ism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felhasználónév.
        /// </summary>
        public static string felhasznalo_nev {
            get {
                return ResourceManager.GetString("felhasznalo_nev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fő.
        /// </summary>
        public static string fo {
            get {
                return ResourceManager.GetString("fo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Főoldal.
        /// </summary>
        public static string fooldal {
            get {
                return ResourceManager.GetString("fooldal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iskola / Kar.
        /// </summary>
        public static string iskola {
            get {
                return ResourceManager.GetString("iskola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jelszó.
        /// </summary>
        public static string jelszo {
            get {
                return ResourceManager.GetString("jelszo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapcsolat.
        /// </summary>
        public static string kapcsolat {
            get {
                return ResourceManager.GetString("kapcsolat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Német nyelvű ügyintézés.
        /// </summary>
        public static string kapcsolat_de {
            get {
                return ResourceManager.GetString("kapcsolat_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magyar nyelvű ügyintézés.
        /// </summary>
        public static string kapcsolat_hu {
            get {
                return ResourceManager.GetString("kapcsolat_hu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kijelentkezés.
        /// </summary>
        public static string kijelentkezes {
            get {
                return ResourceManager.GetString("kijelentkezes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Küldés.
        /// </summary>
        public static string kuldes {
            get {
                return ResourceManager.GetString("kuldes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Munka.
        /// </summary>
        public static string munka {
            get {
                return ResourceManager.GetString("munka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A munkába lépés éve.
        /// </summary>
        public static string munka_kezdet {
            get {
                return ResourceManager.GetString("munka_kezdet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Munkahelyi pozició.
        /// </summary>
        public static string munka_pozicio {
            get {
                return ResourceManager.GetString("munka_pozicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilépés éve.
        /// </summary>
        public static string munka_vege {
            get {
                return ResourceManager.GetString("munka_vege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Munkaadó.
        /// </summary>
        public static string munkahely {
            get {
                return ResourceManager.GetString("munkahely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Munkát kínálok.
        /// </summary>
        public static string munkat_kinalok {
            get {
                return ResourceManager.GetString("munkat_kinalok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nem vagy bejelentkezve!.
        /// </summary>
        public static string nem_vagy_bejelentkezve {
            get {
                return ResourceManager.GetString("nem_vagy_bejelentkezve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programozó ismeretek.
        /// </summary>
        public static string prog_ism {
            get {
                return ResourceManager.GetString("prog_ism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regisztráció.
        /// </summary>
        public static string regisztracio {
            get {
                return ResourceManager.GetString("regisztracio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rólunk.
        /// </summary>
        public static string rolunk {
            get {
                return ResourceManager.GetString("rolunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szak.
        /// </summary>
        public static string szak {
            get {
                return ResourceManager.GetString("szak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szolgáltatásaink.
        /// </summary>
        public static string szolgaltatasaink {
            get {
                return ResourceManager.GetString("szolgaltatasaink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tanulmányok kezdete.
        /// </summary>
        public static string tanulmany_kezdete {
            get {
                return ResourceManager.GetString("tanulmany_kezdete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tanulmányok befejezése.
        /// </summary>
        public static string tanulmany_vege {
            get {
                return ResourceManager.GetString("tanulmany_vege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Település.
        /// </summary>
        public static string telepules {
            get {
                return ResourceManager.GetString("telepules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tudásszint.
        /// </summary>
        public static string tudasszint {
            get {
                return ResourceManager.GetString("tudasszint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üdvözlünk az oldalon!.
        /// </summary>
        public static string udv_az_oldalon {
            get {
                return ResourceManager.GetString("udv_az_oldalon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üzlet neve.
        /// </summary>
        public static string uzlet {
            get {
                return ResourceManager.GetString("uzlet", resourceCulture);
            }
        }
    }
}
